spring.application.name=carrito-service
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

microservicios.usuario.url=http://localhost:9091
microservicios.pago.url=http://localhost:9093