
spring.application.name=carrito-service
server.port=8081


# Configuración de PostgreSQL - CORREGIDA
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=admin
<<<<<<< HEAD


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
=======
spring.datasource.driver-class-name=org.postgresql.Driver
>>>>>>> eb0f305b7911991f9645f69c3337dc42faae76c4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


microservicios.usuario.url=http://localhost:9091
microservicios.pago.url=http://localhost:9093