spring.application.name=libros-service
server.port=9094

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=elinge
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

microservicios.usuario.url=http://localhost:9091
microservicios.pago.url=http://localhost:9093